// Generated by tools/generate-builtins.js from builtins.json. Do not edit.
package analysis

var builtinDocs = map[string]builtinDoc{
	"dup": {
		StackEffect: "x -- x x",
		Description: "Duplicate the top stack item.",
	},
	"drop": {
		StackEffect: "x --",
		Description: "Discard the top stack item.",
	},
	"swap": {
		StackEffect: "a b -- b a",
		Description: "Swap the top two stack items.",
	},
	"over": {
		StackEffect: "a b -- a b a",
		Description: "Copy the second stack item to the top.",
	},
	"rot": {
		StackEffect: "a b c -- b c a",
		Description: "Rotate the top three stack items.",
	},
	"swapd": {
		StackEffect: "a b c -- b a c",
		Description: "Swap the two items below the top stack item.",
	},
	"nip": {
		StackEffect: "a b -- b",
		Description: "Discard the second stack item and keep the top item.",
	},
	"tuck": {
		StackEffect: "a b -- b a b",
		Description: "Copy the top stack item beneath the next item.",
	},
	"pick": {
		StackEffect: "... n -- ... x",
		Description: "Copy the stack item at depth n to the top.",
	},
	"roll": {
		StackEffect: "... n -- ...",
		Description: "Move the stack item at depth n to the top.",
	},
	"empty": {
		StackEffect: "--",
		Description: "Clear the entire data stack.",
	},
	"+": {
		StackEffect: "a b -- a+b",
		Description: "Add two numeric values.",
	},
	"-": {
		StackEffect: "a b -- a-b",
		Description: "Subtract the top value from the next value.",
	},
	"*": {
		StackEffect: "a b -- a*b",
		Description: "Multiply two numeric values.",
	},
	"/": {
		StackEffect: "a b -- a/b",
		Description: "Divide the next value by the top value.",
	},
	"%": {
		StackEffect: "a b -- remainder",
		Description: "Compute the truncating remainder of integer division.",
	},
	"mod": {
		StackEffect: "a b -- modulo",
		Description: "Compute Euclidean modulo, returning a non-negative result.",
	},
	"neg": {
		StackEffect: "x -- -x",
		Description: "Negate the top numeric value.",
	},
	"abs": {
		StackEffect: "x -- |x|",
		Description: "Replace a number with its absolute value.",
	},
	"max": {
		StackEffect: "a b -- max",
		Description: "Keep the larger of two values.",
	},
	"min": {
		StackEffect: "a b -- min",
		Description: "Keep the smaller of two values.",
	},
	"sqrt": {
		StackEffect: "n -- f",
		Description: "Compute the square root of a numeric value.",
	},
	"pow": {
		StackEffect: "base exp -- f",
		Description: "Raise a numeric base to a numeric exponent.",
	},
	"exp": {
		StackEffect: "n -- f",
		Description: "Compute e raised to a numeric value.",
	},
	"log": {
		StackEffect: "n -- f",
		Description: "Compute the natural logarithm of a numeric value.",
	},
	"log10": {
		StackEffect: "n -- f",
		Description: "Compute the base-10 logarithm of a numeric value.",
	},
	"sin": {
		StackEffect: "n -- f",
		Description: "Compute the sine of a numeric value in radians.",
	},
	"cos": {
		StackEffect: "n -- f",
		Description: "Compute the cosine of a numeric value in radians.",
	},
	"tan": {
		StackEffect: "n -- f",
		Description: "Compute the tangent of a numeric value in radians.",
	},
	"floor": {
		StackEffect: "n -- i",
		Description: "Round a numeric value down to an integer.",
	},
	"ceil": {
		StackEffect: "n -- i",
		Description: "Round a numeric value up to an integer.",
	},
	"round": {
		StackEffect: "n -- i",
		Description: "Round a numeric value to the nearest integer.",
	},
	"pred": {
		StackEffect: "i -- i-1",
		Description: "Decrement an integer by one.",
	},
	"succ": {
		StackEffect: "i -- i+1",
		Description: "Increment an integer by one.",
	},
	"square": {
		StackEffect: "n -- n*n",
		Description: "Square an integer or float.",
	},
	"cube": {
		StackEffect: "n -- n*n*n",
		Description: "Cube an integer or float.",
	},
	"pi": {
		StackEffect: "-- f",
		Description: "Push pi as a floating-point value.",
	},
	"e": {
		StackEffect: "-- f",
		Description: "Push Euler's number as a floating-point value.",
	},
	"tau": {
		StackEffect: "-- f",
		Description: "Push tau, equal to two pi, as a floating-point value.",
	},
	"inf": {
		StackEffect: "-- f",
		Description: "Push positive infinity as a floating-point value.",
	},
	"nan": {
		StackEffect: "-- f",
		Description: "Push NaN as a floating-point value.",
	},
	"inf?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is an infinite float.",
	},
	"nan?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is a NaN float.",
	},
	"rand": {
		StackEffect: "-- n",
		Description: "Push a random integer.",
	},
	"and": {
		StackEffect: "a b -- res",
		Description: "Logical AND for booleans, bitwise AND for integers.",
	},
	"or": {
		StackEffect: "a b -- res",
		Description: "Logical OR for booleans, bitwise OR for integers.",
	},
	"xor": {
		StackEffect: "a b -- res",
		Description: "Logical XOR for booleans, bitwise XOR for integers.",
	},
	"not": {
		StackEffect: "a -- res",
		Description: "Logical NOT for booleans, bitwise NOT for integers.",
	},
	"shl": {
		StackEffect: "n bits -- n<<bits",
		Description: "Left shift an integer by the specified number of bits.",
	},
	"shr": {
		StackEffect: "n bits -- n>>bits",
		Description: "Right shift an integer by the specified number of bits.",
	},
	"==": {
		StackEffect: "a b -- bool",
		Description: "Compare two values for equality. Vectors and lists compare structurally.",
	},
	"!=": {
		StackEffect: "a b -- bool",
		Description: "Compare two values for inequality. Vectors and lists compare structurally.",
	},
	"<": {
		StackEffect: "a b -- bool",
		Description: "Check numeric or string ordering: whether the next value is less than the top value.",
	},
	">": {
		StackEffect: "a b -- bool",
		Description: "Check numeric or string ordering: whether the next value is greater than the top value.",
	},
	"<=": {
		StackEffect: "a b -- bool",
		Description: "Check numeric or string ordering: whether the next value is less than or equal to the top value.",
	},
	">=": {
		StackEffect: "a b -- bool",
		Description: "Check numeric or string ordering: whether the next value is greater than or equal to the top value.",
	},
	"exec": {
		StackEffect: "callable -- ...",
		Description: "Run a quotation or a defined word named by a symbol or call instruction.",
	},
	"i": {
		StackEffect: "callable -- ...",
		Description: "Alias for exec. Run a quotation or a defined word named by a symbol or call instruction.",
	},
	"if": {
		StackEffect: "bool|callable callable --",
		Description: "Execute the callable when the condition is true.",
	},
	"ifelse": {
		StackEffect: "bool|callable callable callable --",
		Description: "Execute one of two callables based on the condition.",
	},
	"while": {
		StackEffect: "callable callable --",
		Description: "Repeat while the condition callable yields true.",
	},
	"cond": {
		StackEffect: "clauses --",
		Description: "Evaluate predicate/body clause pairs and execute the body for the first true predicate.",
	},
	"try": {
		StackEffect: "... body handler -- ...",
		Description: "Execute body and, if it raises a runtime error, restore the surrounding stack and run handler with the error message; handler errors, interrupts, and exit propagate without rollback.",
	},
	"error": {
		StackEffect: "string --",
		Description: "Raise a runtime error using a string message; unless caught by try, completed stack effects are not rolled back.",
	},
	"app2": {
		StackEffect: "x y callable -- x' y'",
		Description: "Apply a callable independently to two stack items.",
	},
	"infra": {
		StackEffect: "vector callable -- vector",
		Description: "Execute a callable using a vector as a temporary stack and collect the resulting stack into a vector.",
	},
	"cleave": {
		StackEffect: "x callable-vector -- ...",
		Description: "Apply several callables independently to the same value and leave all outputs on the stack.",
	},
	"construct": {
		StackEffect: "x callable-vector -- vector",
		Description: "Apply several callables independently to the same value and collect their outputs into one vector.",
	},
	"replicate": {
		StackEffect: "n callable -- vector",
		Description: "Execute a callable n times and collect exactly one result from each execution into a vector.",
	},
	"times": {
		StackEffect: "... n callable -- ...",
		Description: "Execute a callable a fixed number of times, threading the current stack through each run.",
	},
	"dip": {
		StackEffect: "x callable -- x",
		Description: "Execute a callable while hiding the top item of the stack.",
	},
	"keep": {
		StackEffect: "x callable -- x ...",
		Description: "Execute a callable while keeping a copy of the top item on the stack.",
	},
	"bi": {
		StackEffect: "x callable callable -- ... ...",
		Description: "Apply two callables independently to the same stack item.",
	},
	"linrec": {
		StackEffect: "callable callable callable callable -- ...",
		Description: "Linear recursion scheme: run then when pred is true, otherwise run rec1, recurse, then run rec2.",
	},
	"binrec": {
		StackEffect: "callable callable callable callable -- ...",
		Description: "Binary recursion scheme: run then when pred is true, otherwise run rec1, recurse over two produced values, then run rec2.",
	},
	"genrec": {
		StackEffect: "callable callable callable callable -- ...",
		Description: "General recursion scheme: run then when pred is true, otherwise run before, recurse, then run after.",
	},
	"treerec": {
		StackEffect: "tree callable callable -- result",
		Description: "Recursively transform a tree using leaf and node callables.",
	},
	"each": {
		StackEffect: "... vector|list|string callable -- ...",
		Description: "Execute a callable for each item in a vector or list, or each byte in a string, threading the current stack through each run.",
	},
	"map": {
		StackEffect: "vector|list|string callable -- vector|list|string",
		Description: "Apply a callable to each sequence item and preserve the input sequence family.",
	},
	"fold": {
		StackEffect: "init vector|list|string callable -- acc",
		Description: "Reduce a vector, list, or string from left to right by applying a callable to the accumulator and each item.",
	},
	"filter": {
		StackEffect: "vector|list|string callable -- vector|list|string",
		Description: "Keep sequence items for which a predicate callable returns true.",
	},
	"some": {
		StackEffect: "vector|list|string callable -- bool",
		Description: "Check whether any sequence item satisfies a predicate callable.",
	},
	"all": {
		StackEffect: "vector|list|string callable -- bool",
		Description: "Check whether every sequence item satisfies a predicate callable.",
	},
	"split": {
		StackEffect: "vector|list|string callable -- true false | string sep -- vector",
		Description: "Partition a vector, list, or string with a predicate callable, or split a string using a separator.",
	},
	"merge": {
		StackEffect: "seq seq callable -- seq",
		Description: "Merge two sorted sequences of the same type. The ordering predicate leaves a boolean; after reading it, Toy restores the surrounding stack.",
	},
	">vector": {
		StackEffect: "vector|list|string -- vector",
		Description: "Build a vector from a sequence, preserving order.",
	},
	">list": {
		StackEffect: "vector|list|string -- list",
		Description: "Build a list from a sequence, preserving order.",
	},
	">string": {
		StackEffect: "vector|list|string -- string",
		Description: "Build a string from a sequence of one-character strings.",
	},
	">deque": {
		StackEffect: "vector|list|string -- deque",
		Description: "Build a deque from a vector, list, or string, preserving front-to-back order.",
	},
	"at": {
		StackEffect: "vector|string idx -- value|char",
		Description: "Fetch a vector element or one-character string by index.",
	},
	"set-at": {
		StackEffect: "vector idx value -- vector | string idx char -- string",
		Description: "Return a collection with one element or character replaced.",
	},
	"slice": {
		StackEffect: "vector|string start end -- vector|string",
		Description: "Return a sub-vector or substring from start up to, but not including, end.",
	},
	"take": {
		StackEffect: "vector|list|string n -- vector|list|string",
		Description: "Return the first n items or characters from a vector, list, or string.",
	},
	"skip": {
		StackEffect: "vector|list|string n -- vector|list|string",
		Description: "Return a vector, list, or string with the first n items or characters removed.",
	},
	"len": {
		StackEffect: "collection -- n",
		Description: "Get the length of a vector, list, string, map, set, deque, or priority queue.",
	},
	"concat": {
		StackEffect: "vector vector -- vector | list list -- list | string string -- string",
		Description: "Concatenate two vectors, two lists, or two strings.",
	},
	"reverse": {
		StackEffect: "vector|list|string -- vector|list|string",
		Description: "Return a sequence with its items or bytes in reverse order.",
	},
	"split-mid": {
		StackEffect: "vector|list|string -- left right",
		Description: "Split a vector, list, or string into left and right halves.",
	},
	"range": {
		StackEffect: "start end -- vector",
		Description: "Create a vector of integers from start up to, but not including, end.",
	},
	"empty?": {
		StackEffect: "collection -- bool",
		Description: "Check whether a vector, list, string, map, set, deque, or priority queue is empty.",
	},
	"first": {
		StackEffect: "vector|list|string|deque -- x|char",
		Description: "Consume a non-empty ordered collection and return its first item.",
	},
	"last": {
		StackEffect: "vector|list|string|deque -- x|char",
		Description: "Consume a non-empty ordered collection and return its last item.",
	},
	"rest": {
		StackEffect: "vector|list|string -- rest",
		Description: "Get all sequence items except the first one.",
	},
	"uncons": {
		StackEffect: "vector|list|string -- head tail",
		Description: "Destructure a sequence into its head and tail.",
	},
	"cons": {
		StackEffect: "x vector|list -- vector|list | char string -- string",
		Description: "Add one item to the front of a vector or list, or one-byte string to the front of a string.",
	},
	"push-front": {
		StackEffect: "deque item -- deque",
		Description: "Return a deque with item added at the front.",
	},
	"push-back": {
		StackEffect: "vector|list|string|deque item -- vector|list|string|deque",
		Description: "Return a sequence or deque with one item added at the back. String items are one-byte strings.",
	},
	"pop-front": {
		StackEffect: "deque -- deque item",
		Description: "Return the updated deque followed by the removed front item.",
	},
	"pop-back": {
		StackEffect: "vector|deque -- vector|deque item",
		Description: "Return the updated vector or deque followed by the removed back item.",
	},
	"contains?": {
		StackEffect: "vector|list item -- bool | string substring -- bool",
		Description: "Check item membership in a vector/list or substring presence in a string.",
	},
	"index-of": {
		StackEffect: "vector|list item -- idx|-1 | string substring -- idx|-1",
		Description: "Return the first item or substring index, or -1 when absent.",
	},
	"unique": {
		StackEffect: "vector|list|string -- vector|list|string",
		Description: "Remove duplicate sequence items, preserving the first occurrence and input family.",
	},
	"sort": {
		StackEffect: "vector|list|string -- vector|list|string",
		Description: "Sort numbers or strings in natural ascending order, preserving the input family.",
	},
	"join": {
		StackEffect: "vector|list sep -- string",
		Description: "Join a vector or list of strings using a separator.",
	},
	"trim": {
		StackEffect: "string -- string",
		Description: "Remove leading and trailing whitespace from a string.",
	},
	"starts-with?": {
		StackEffect: "string prefix -- bool",
		Description: "Check whether a byte string starts with a prefix.",
	},
	"ends-with?": {
		StackEffect: "string suffix -- bool",
		Description: "Check whether a byte string ends with a suffix.",
	},
	"replace": {
		StackEffect: "string old new -- string",
		Description: "Replace every non-overlapping occurrence of a non-empty byte substring from left to right.",
	},
	"format": {
		StackEffect: "args... format -- string",
		Description: "Return a string by substituting values into {} placeholders; {{ and }} produce literal braces.",
	},
	"upper": {
		StackEffect: "string -- string",
		Description: "Convert a string to uppercase.",
	},
	"lower": {
		StackEffect: "string -- string",
		Description: "Convert a string to lowercase.",
	},
	"char?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is a one-byte string.",
	},
	">char": {
		StackEffect: "n -- char",
		Description: "Construct a one-character string from an integer code between 0 and 255.",
	},
	"char-code": {
		StackEffect: "char -- n",
		Description: "Return the unsigned integer code of a one-character string.",
	},
	"letter?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is a one-byte alphabetic string.",
	},
	"digit?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is a one-byte digit string.",
	},
	"alnum?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is a one-byte alphabetic or digit string.",
	},
	"space?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is a one-byte whitespace string.",
	},
	"upper?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is a one-byte uppercase string.",
	},
	"lower?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is a one-byte lowercase string.",
	},
	"punct?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is a one-byte punctuation string.",
	},
	">map": {
		StackEffect: "pairs -- map",
		Description: "Build a map from a vector or list of two-item key/value pairs. Duplicate keys are an error.",
	},
	">set": {
		StackEffect: "vector|list|string -- set",
		Description: "Build a set from a vector, list, or string, collapsing duplicate items.",
	},
	"has?": {
		StackEffect: "map key -- bool | set item -- bool",
		Description: "Check whether a map contains a key or a set contains an item.",
	},
	"get": {
		StackEffect: "map key -- value",
		Description: "Fetch a map value. Missing keys are runtime errors; use get-or or has? when absence is expected.",
	},
	"get-or": {
		StackEffect: "map key default -- value",
		Description: "Fetch a map value, returning the supplied default when the key is absent.",
	},
	"assoc": {
		StackEffect: "map key value -- map",
		Description: "Return a map with key associated to value.",
	},
	"dissoc": {
		StackEffect: "map key -- map",
		Description: "Return a map without key. Missing keys leave the map unchanged.",
	},
	"keys": {
		StackEffect: "map -- vector",
		Description: "Return map keys in insertion order.",
	},
	"values": {
		StackEffect: "map -- vector",
		Description: "Return map values in insertion order.",
	},
	"pairs": {
		StackEffect: "map|pqueue -- vector",
		Description: "Return map key/value pairs in insertion order or priority/value pairs in priority order.",
	},
	"items": {
		StackEffect: "set -- vector | deque -- vector",
		Description: "Return set items in insertion order or deque items from front to back.",
	},
	"insert": {
		StackEffect: "set item -- set",
		Description: "Return a set containing item. An existing item leaves the set and its insertion order unchanged.",
	},
	"remove": {
		StackEffect: "set item -- set",
		Description: "Return a set without item. Missing items leave the set unchanged.",
	},
	"union": {
		StackEffect: "set set -- set",
		Description: "Return items from either set, preserving left order then unseen right items.",
	},
	"intersection": {
		StackEffect: "set set -- set",
		Description: "Return items present in both sets, preserving left-set order.",
	},
	"difference": {
		StackEffect: "set set -- set",
		Description: "Return items from the left set that are absent from the right set.",
	},
	"symmetric-difference": {
		StackEffect: "set set -- set",
		Description: "Return left-only items followed by right-only items.",
	},
	"subset?": {
		StackEffect: "set set -- bool",
		Description: "Check whether the left set is a subset of the right set, including equality.",
	},
	"proper-subset?": {
		StackEffect: "set set -- bool",
		Description: "Check whether the left set is a strict subset of the right set.",
	},
	"superset?": {
		StackEffect: "set set -- bool",
		Description: "Check whether the left set is a superset of the right set, including equality.",
	},
	"proper-superset?": {
		StackEffect: "set set -- bool",
		Description: "Check whether the left set is a strict superset of the right set.",
	},
	"disjoint?": {
		StackEffect: "set set -- bool",
		Description: "Check whether the sets have no items in common.",
	},
	">pqueue": {
		StackEffect: "pairs -- pqueue",
		Description: "Build a priority queue from two-item [priority value] or (priority value) pairs. Lower priorities are returned first.",
	},
	"pq-push": {
		StackEffect: "pqueue priority value -- pqueue",
		Description: "Return a priority queue with value inserted at a finite numeric priority.",
	},
	"pq-peek": {
		StackEffect: "pqueue -- pqueue priority value",
		Description: "Leave a priority queue unchanged and copy its next priority/value pair to the top.",
	},
	"pq-pop": {
		StackEffect: "pqueue -- pqueue priority value",
		Description: "Return the updated priority queue followed by the removed priority and value.",
	},
	"type-of": {
		StackEffect: "x -- string",
		Description: "Push a string naming the input type.",
	},
	"bool?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is a boolean.",
	},
	"int?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is an integer.",
	},
	"float?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is a float.",
	},
	">int": {
		StackEffect: "int|float|string -- int",
		Description: "Convert strict decimal text or an exactly integral finite float to a signed 64-bit integer.",
	},
	">float": {
		StackEffect: "int|float|string -- float",
		Description: "Convert an integer or strict decimal numeric text to a double-precision float.",
	},
	"string?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is a string.",
	},
	"symbol?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is a symbol.",
	},
	"call?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is a call instruction, the value stored for a bare word inside a quotation.",
	},
	"vector?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is a vector.",
	},
	"list?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is a linked list.",
	},
	"map?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is a map.",
	},
	"set?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is a set.",
	},
	"deque?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is a deque.",
	},
	"pqueue?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is a priority queue.",
	},
	"resource?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is an opaque foreign resource.",
	},
	"number?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input is an integer or float.",
	},
	"sequence?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input can be iterated as a sequence: vector, list, or string.",
	},
	"callable?": {
		StackEffect: "x -- bool",
		Description: "Check whether the input can be executed now: a vector quotation, symbol, or call naming a defined word.",
	},
	"def": {
		StackEffect: "'name block --",
		Description: "Bind a symbol to a block definition.",
	},
	"private": {
		StackEffect: "'name --",
		Description: "Make a package word private. Package definitions are public by default.",
	},
	"word?": {
		StackEffect: "symbol -- bool",
		Description: "Check whether a symbol names a dictionary word.",
	},
	"var?": {
		StackEffect: "symbol -- bool",
		Description: "Check whether a symbol names a visible dynamic capture.",
	},
	"body": {
		StackEffect: "'name -- quot",
		Description: "Push the quotation body for a user-defined word.",
	},
	">symbol": {
		StackEffect: "string|call -- symbol",
		Description: "Convert text or a call instruction to a symbol.",
	},
	">call": {
		StackEffect: "symbol -- call",
		Description: "Convert a symbol to a call instruction that can be inserted into a quotation.",
	},
	"name": {
		StackEffect: "symbol -- string",
		Description: "Convert a symbol to a string.",
	},
	"words": {
		StackEffect: "-- vector",
		Description: "Push a sorted vector of dictionary word names as symbols.",
	},
	"see": {
		StackEffect: "'name -- string",
		Description: "Push a source-like representation of a word definition.",
	},
	"doc": {
		StackEffect: "'name -- string",
		Description: "Push documentation for a defined word as a string.",
	},
	"search-words": {
		StackEffect: "query -- vector",
		Description: "Push a sorted vector of symbols whose names or docs match query.",
	},
	"repr": {
		StackEffect: "x -- string",
		Description: "Return a source-style representation of a value, with string bytes escaped.",
	},
	"printf": {
		StackEffect: "x -- | args... format --",
		Description: "Print one value without a newline, interpreting {} placeholders only when the top value is a format string.",
	},
	"print": {
		StackEffect: "x --",
		Description: "Print one value literally, followed by a newline.",
	},
	".": {
		StackEffect: "x -- x",
		Description: "Print the top stack item.",
	},
	".s": {
		StackEffect: "--",
		Description: "Print the current stack state.",
	},
	".S": {
		StackEffect: "--",
		Description: "Print the current stack using source-style value formatting.",
	},
	"read-key": {
		StackEffect: "-- char",
		Description: "Read one byte from input as a one-character string.",
	},
	"read-line": {
		StackEffect: "-- string",
		Description: "Read one line from stdin without its trailing newline.",
	},
	"clear": {
		StackEffect: "--",
		Description: "Clear the terminal screen.",
	},
	"package": {
		StackEffect: "'name --",
		Description: "Declare the package name at directory scope.",
	},
	"import": {
		StackEffect: "path --",
		Description: "Import one package from an explicit directory path or core: locator. In package source this is a top-level declaration; in the REPL it executes immediately.",
	},
	"import-as": {
		StackEffect: "path 'alias --",
		Description: "Import one package under an explicit local alias. In package source this is a top-level declaration; in the REPL it executes immediately.",
	},
	"read-file": {
		StackEffect: "path -- string",
		Description: "Read the entire content of a file into a string.",
	},
	"write-file": {
		StackEffect: "path content --",
		Description: "Write string content to a file.",
	},
	"delete-file": {
		StackEffect: "path --",
		Description: "Delete a file.",
	},
	"read-lines": {
		StackEffect: "path -- vector",
		Description: "Read a file and return a vector of its lines.",
	},
	"file-exists?": {
		StackEffect: "path -- bool",
		Description: "Check if a file exists.",
	},
	"argc": {
		StackEffect: "-- n",
		Description: "Push the number of script arguments.",
	},
	"argv": {
		StackEffect: "-- vector",
		Description: "Push script arguments as a vector of strings.",
	},
	"env?": {
		StackEffect: "key -- bool",
		Description: "Check whether an environment variable is set.",
	},
	"get-env": {
		StackEffect: "key -- value",
		Description: "Read an environment variable. Fails when it is not set; use env? when absence is expected.",
	},
	"set-env": {
		StackEffect: "key value --",
		Description: "Set an environment variable, failing if the operation is rejected.",
	},
	"pwd": {
		StackEffect: "-- string",
		Description: "Push the current working directory.",
	},
	"shell": {
		StackEffect: "cmd -- output status",
		Description: "Run a shell command and push its output followed by its exit status.",
	},
	"exit": {
		StackEffect: "--",
		Description: "Terminate the interpreter.",
	},
	"sleep": {
		StackEffect: "ms --",
		Description: "Pause execution for a number of milliseconds.",
	},
	"unix-time": {
		StackEffect: "-- seconds",
		Description: "Push whole seconds since 1970-01-01 00:00:00 UTC.",
	},
	"local-time": {
		StackEffect: "-- map",
		Description: "Push the current local year, month, day, hour, minute, and second.",
	},
	"utc-time": {
		StackEffect: "-- map",
		Description: "Push the current UTC year, month, day, hour, minute, and second.",
	},
	"cpu-time": {
		StackEffect: "-- seconds",
		Description: "Push process CPU time in seconds as a float.",
	},
	"monotonic-ns": {
		StackEffect: "-- nanoseconds",
		Description: "Push a monotonic wall-clock reading in integer nanosecond units; actual resolution is platform-dependent.",
	},
}
