// Generated by tools/generate-builtins.js from core package words.json metadata. Do not edit.
package analysis

var corePackageDocs = map[string]corePackageDoc{
	"core:ffi": {
		Name: "ffi",
		Words: map[string]builtinDoc{
			"open": {
				StackEffect: "path -- library",
				Description: "Open a shared library and return a managed library handle.",
			},
			"bind": {
				StackEffect: "library symbol signature -- function",
				Description: "Resolve a library symbol using an input-to-output signature such as `cstr -> usize`.",
			},
			"call": {
				StackEffect: "args... function -- result?",
				Description: "Call a bound foreign function, consuming its arguments and function handle.",
			},
		},
	},
	"core:json": {
		Name: "json",
		Words: map[string]builtinDoc{
			"null": {
				StackEffect: "-- null",
				Description: "Return the explicit package-specific value used for JSON null.",
			},
			"null?": {
				StackEffect: "value -- bool",
				Description: "Check whether a value is the package-specific JSON null value.",
			},
			"decode": {
				StackEffect: "string -- value",
				Description: "Decode one strict UTF-8 JSON document or raise an error.",
			},
			"encode": {
				StackEffect: "value -- string",
				Description: "Encode a supported Toy value as compact UTF-8 JSON or raise an error.",
			},
		},
	},
	"core:random": {
		Name: "random",
		Words: map[string]builtinDoc{
			"seed": {
				StackEffect: "seed --",
				Description: "Deterministically reseed the interpreter's pseudorandom stream from an integer.",
			},
			"int": {
				StackEffect: "lower upper -- n",
				Description: "Return an unbiased integer from lower up to, but not including, upper.",
			},
			"float": {
				StackEffect: "-- f",
				Description: "Return a pseudorandom float greater than or equal to zero and less than one.",
			},
			"choice": {
				StackEffect: "sequence -- item",
				Description: "Return one uniformly selected item from a non-empty vector, list, or string.",
			},
			"shuffle": {
				StackEffect: "sequence -- sequence",
				Description: "Return a uniformly shuffled vector, list, or string while preserving its sequence type.",
			},
		},
	},
}
