// Generated by tools/generate-builtins.js from core package words.json metadata. Do not edit.
package analysis

var corePackageDocs = map[string]corePackageDoc{
	"core:ffi": {
		Name: "ffi",
		Words: map[string]builtinDoc{
			"open": {
				StackEffect: "path -- library",
				Description: "Open a shared library and return a managed library handle.",
			},
			"bind": {
				StackEffect: "library symbol signature -- function",
				Description: "Resolve a library symbol using an input-to-output signature such as `cstr -> usize`.",
			},
			"call": {
				StackEffect: "args... function -- result?",
				Description: "Call a bound foreign function, consuming its arguments and function handle.",
			},
		},
	},
}
