// Generated by tools/generate-builtins.js from core package words.json metadata. Do not edit.
package analysis

var corePackageDocs = map[string]corePackageDoc{
	"core:ffi": {
		Name: "ffi",
		Words: map[string]builtinDoc{
			"open": {
				StackEffect: "path -- library",
				Description: "Open a shared library and return a managed library handle.",
			},
			"bind": {
				StackEffect: "library symbol signature -- function",
				Description: "Resolve a library symbol using an input-to-output signature such as `cstr -> usize`.",
			},
			"call": {
				StackEffect: "args... function -- result?",
				Description: "Call a bound foreign function, consuming its arguments and function handle.",
			},
		},
	},
	"core:json": {
		Name: "json",
		Words: map[string]builtinDoc{
			"null": {
				StackEffect: "-- null",
				Description: "Return the explicit package-specific value used for JSON null.",
			},
			"null?": {
				StackEffect: "value -- bool",
				Description: "Check whether a value is the package-specific JSON null value.",
			},
			"decode": {
				StackEffect: "string -- value",
				Description: "Decode one strict UTF-8 JSON document or raise an error.",
			},
			"encode": {
				StackEffect: "value -- string",
				Description: "Encode a supported Toy value as compact UTF-8 JSON or raise an error.",
			},
		},
	},
}
