const fs = require('fs');
const path = require('path');

const generatedComment =
  'Generated by toy-bindgen. Do not edit.';
const supportedTypes = new Set([
  'void',
  'bool',
  'i8',
  'u8',
  'i16',
  'u16',
  'i32',
  'u32',
  'i64',
  'u64',
  'isize',
  'usize',
  'f32',
  'f64',
  'cstr',
]);
const statusTypes = new Set([
  'i8',
  'u8',
  'i16',
  'u16',
  'i32',
  'u32',
  'i64',
  'isize',
]);
const integerTypes = new Set([
  'i8',
  'u8',
  'i16',
  'u16',
  'i32',
  'u32',
  'i64',
  'u64',
  'isize',
  'usize',
]);

function isObject(value) {
  return value && typeof value === 'object' && !Array.isArray(value);
}

function fail(message) {
  throw new Error(message);
}

function requireString(value, field) {
  if (typeof value !== 'string' || value.length === 0) {
    fail(`${field} must be a non-empty string`);
  }
}

function requireKeys(value, allowed, field) {
  for (const key of Object.keys(value)) {
    if (!allowed.has(key)) fail(`${field}.${key} is not supported`);
  }
}

function hasField(value, field) {
  return Object.prototype.hasOwnProperty.call(value, field);
}

function validateType(value, field, allowVoid) {
  requireString(value, field);
  if (!supportedTypes.has(value)) fail(`${field} has unsupported type '${value}'`);
  if (value === 'void' && !allowVoid) fail(`${field} cannot be void`);
}

function validateCIdentifier(value, field) {
  requireString(value, field);
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(value)) {
    fail(`${field} is not a C identifier`);
  }
}

function validateResourceName(value, field) {
  requireString(value, field);
  if (!/^[A-Za-z_][A-Za-z0-9_-]*$/.test(value)) {
    fail(`${field} is not a local resource name`);
  }
}

function validateCPointerType(value, field) {
  requireString(value, field);
  const pointerType =
    /^(?:(?:const|volatile)\s+)*(?:(?:struct|union)\s+)?[A-Za-z_][A-Za-z0-9_]*(?:\s*\*+)+$/;
  if (!pointerType.test(value)) {
    fail(`${field} must be a C pointer type`);
  }
}

function resourceMap(manifest) {
  return new Map((manifest.resources || []).map((resource, index) => [
    resource.name,
    {...resource, index},
  ]));
}

function requireResource(resources, name, field) {
  validateResourceName(name, field);
  if (!resources.has(name)) fail(`${field} references unknown resource '${name}'`);
}

function validateStatusCode(value, type, field) {
  if (!Number.isSafeInteger(value)) fail(`${field} must be a safe integer`);
  const ranges = {
    i8: [-128, 127],
    u8: [0, 255],
    i16: [-32768, 32767],
    u16: [0, 65535],
    i32: [-2147483648, 2147483647],
    u32: [0, 4294967295],
    isize: [-2147483648, 2147483647],
  };
  if (ranges[type] && (value < ranges[type][0] || value > ranges[type][1])) {
    fail(`${field} is outside ${type}'s range`);
  }
}

function validateConstantValue(value, type, field) {
  if (type === 'bool') {
    if (typeof value !== 'boolean') fail(`${field} must be a boolean`);
    return;
  }
  if (type === 'f32' || type === 'f64') {
    if (typeof value !== 'number' || !Number.isFinite(value)) {
      fail(`${field} must be a finite number`);
    }
    if (type === 'f32' && Math.abs(value) > 3.402823466e38) {
      fail(`${field} is outside f32's range`);
    }
    return;
  }
  if (!integerTypes.has(type)) {
    fail(`${field} has unsupported constant type '${type}'`);
  }
  if (!Number.isSafeInteger(value)) fail(`${field} must be a safe integer`);
  if ((type === 'u64' || type === 'usize') && value < 0) {
    fail(`${field} is outside ${type}'s range`);
  }
  validateStatusCode(value, type, field);
}

function validateBytes(value, field, returnValue) {
  if (!isObject(value)) fail(`${field} must be an object`);
  if (returnValue) {
    requireKeys(value, new Set(['lengthFunction', 'lengthType']), field);
    validateCIdentifier(value.lengthFunction, `${field}.lengthFunction`);
    validateType(value.lengthType, `${field}.lengthType`, false);
    if (!integerTypes.has(value.lengthType)) {
      fail(`${field}.lengthType must be an integer type`);
    }
    return;
  }
  requireKeys(value, new Set(['length']), field);
  validateType(value.length, `${field}.length`, false);
  if (!integerTypes.has(value.length)) {
    fail(`${field}.length must be an integer type`);
  }
}

function validateMappedValue(value, field) {
  if (typeof value !== 'boolean') fail(`${field} must be a boolean`);
}

function validateReturn(value, field, resources) {
  if (typeof value === 'string') {
    validateType(value, field, true);
    return;
  }
  if (!isObject(value)) fail(`${field} must be a type string or object`);

  if (hasField(value, 'resource')) {
    requireKeys(value, new Set(['resource']), field);
    requireResource(resources, value.resource, `${field}.resource`);
    return;
  }

  if (hasField(value, 'bytes')) {
    requireKeys(value, new Set(['bytes']), field);
    validateBytes(value.bytes, `${field}.bytes`, true);
    return;
  }

  requireKeys(value, new Set(['status', 'success', 'map', 'error']), field);
  validateType(value.status, `${field}.status`, false);
  if (!statusTypes.has(value.status)) {
    fail(`${field}.status must be a supported status integer type`);
  }
  const hasSuccess = value.success !== undefined;
  const hasMap = value.map !== undefined;
  if (hasSuccess === hasMap) {
    fail(`${field} must contain exactly one of success or map`);
  }
  const codes = new Set();
  if (hasSuccess) {
    if (!Array.isArray(value.success) || value.success.length === 0) {
      fail(`${field}.success must be a non-empty array`);
    }
    for (const [index, code] of value.success.entries()) {
      validateStatusCode(code, value.status, `${field}.success[${index}]`);
      if (codes.has(code)) {
        fail(`${field}.success contains duplicate code ${code}`);
      }
      codes.add(code);
    }
  } else {
    if (!isObject(value.map) || Object.keys(value.map).length === 0) {
      fail(`${field}.map must be a non-empty object`);
    }
    for (const [codeText, mapped] of Object.entries(value.map)) {
      if (!/^-?(?:0|[1-9][0-9]*)$/.test(codeText)) {
        fail(`${field}.map key '${codeText}' is not an integer code`);
      }
      const code = Number(codeText);
      validateStatusCode(code, value.status, `${field}.map.${codeText}`);
      validateMappedValue(mapped, `${field}.map.${codeText}`);
      codes.add(code);
    }
  }
  if (value.error !== undefined) {
    if (!isObject(value.error)) fail(`${field}.error must be an object`);
    requireKeys(value.error, new Set(['function', 'resource']), `${field}.error`);
    validateCIdentifier(value.error.function, `${field}.error.function`);
    requireResource(resources, value.error.resource, `${field}.error.resource`);
  }
}

function validateArgument(value, field, resources) {
  if (typeof value === 'string') {
    validateType(value, field, false);
    return;
  }
  if (!isObject(value)) fail(`${field} must be a type string or object`);
  const kinds = [
    'resource',
    'outResource',
    'const',
    'null',
    'cConstant',
    'bytes',
  ].filter((key) => hasField(value, key));
  if (kinds.length !== 1) {
    fail(`${field} must contain exactly one argument kind`);
  }
  const kind = kinds[0];
  switch (kind) {
    case 'resource':
    case 'outResource':
      requireKeys(value, new Set([kind]), field);
      requireResource(resources, value[kind], `${field}.${kind}`);
      break;
    case 'const':
      requireKeys(value, new Set(['const', 'value']), field);
      validateType(value.const, `${field}.const`, false);
      validateConstantValue(value.value, value.const, `${field}.value`);
      break;
    case 'null':
      requireKeys(value, new Set(['null']), field);
      if (value.null !== true) fail(`${field}.null must be true`);
      break;
    case 'cConstant':
      requireKeys(value, new Set(['cConstant']), field);
      validateCIdentifier(value.cConstant, `${field}.cConstant`);
      break;
    case 'bytes':
      requireKeys(value, new Set(['bytes']), field);
      validateBytes(value.bytes, `${field}.bytes`, false);
      break;
    default:
      fail(`internal error: unsupported argument kind '${kind}'`);
  }
}

function validateManifest(manifest) {
  if (!isObject(manifest)) {
    fail('manifest must be a JSON object');
  }
  requireKeys(
    manifest,
    new Set(['package', 'headers', 'resources', 'functions']),
    'manifest'
  );

  requireString(manifest.package, 'package');
  if (!/^[A-Za-z_][A-Za-z0-9_-]*$/.test(manifest.package)) {
    fail(`invalid Toy package name '${manifest.package}'`);
  }

  if (!Array.isArray(manifest.headers) || manifest.headers.length === 0) {
    fail('headers must be a non-empty array');
  }
  const headers = new Set();
  for (const [index, header] of manifest.headers.entries()) {
    requireString(header, `headers[${index}]`);
    if (!/^[A-Za-z0-9_./+-]+$/.test(header) || header.includes('..')) {
      fail(`headers[${index}] is not a safe include path`);
    }
    if (headers.has(header)) fail(`duplicate header '${header}'`);
    headers.add(header);
  }

  if (manifest.resources !== undefined && !Array.isArray(manifest.resources)) {
    fail('resources must be an array');
  }
  const resourceNames = new Set();
  for (const [index, resource] of (manifest.resources || []).entries()) {
    const field = `resources[${index}]`;
    if (!isObject(resource)) fail(`${field} must be an object`);
    requireKeys(
      resource,
      new Set(['name', 'cType', 'destructor', 'dependsOn']),
      field
    );
    validateResourceName(resource.name, `${field}.name`);
    if (resourceNames.has(resource.name)) {
      fail(`duplicate resource '${resource.name}'`);
    }
    resourceNames.add(resource.name);
    validateCPointerType(resource.cType, `${field}.cType`);
    validateCIdentifier(resource.destructor, `${field}.destructor`);
    if (resource.dependsOn !== undefined) {
      validateResourceName(resource.dependsOn, `${field}.dependsOn`);
    }
  }
  const resources = resourceMap(manifest);
  for (const [index, resource] of (manifest.resources || []).entries()) {
    if (resource.dependsOn === undefined) continue;
    const field = `resources[${index}].dependsOn`;
    requireResource(resources, resource.dependsOn, field);
    if (resource.dependsOn === resource.name) {
      fail(`${field} cannot reference the resource itself`);
    }
  }

  if (!Array.isArray(manifest.functions) || manifest.functions.length === 0) {
    fail('functions must be a non-empty array');
  }
  const words = new Set();
  for (const [index, fn] of manifest.functions.entries()) {
    const field = `functions[${index}]`;
    if (!isObject(fn)) {
      fail(`${field} must be an object`);
    }
    requireKeys(fn, new Set(['name', 'word', 'returns', 'args']), field);
    validateCIdentifier(fn.name, `${field}.name`);
    if (fn.word !== undefined) requireString(fn.word, `${field}.word`);
    const word = fn.word || fn.name;
    if (!/^[A-Za-z_+*%<>=!?-][A-Za-z0-9_+*%<>=!?-]*$/.test(word)) {
      fail(`${field}.word is not a native Toy word name`);
    }
    if (words.has(word)) fail(`duplicate Toy word '${word}'`);
    words.add(word);

    validateReturn(fn.returns, `${field}.returns`, resources);
    if (!Array.isArray(fn.args)) fail(`${field}.args must be an array`);
    if (fn.args.length > 32) fail(`${field}.args supports at most 32 arguments`);
    let outputCount = 0;
    for (const [argIndex, argument] of fn.args.entries()) {
      validateArgument(argument, `${field}.args[${argIndex}]`, resources);
      if (isObject(argument) && argument.outResource !== undefined) {
        outputCount++;
      }
    }
    if (outputCount > 1) {
      fail(`${field}.args supports at most one output resource`);
    }
    if (outputCount > 0 &&
        !(fn.returns === 'void' ||
          (isObject(fn.returns) && fn.returns.status !== undefined))) {
      fail(`${field} output resources require void or status returns`);
    }
    if (outputCount > 0 && isObject(fn.returns) &&
        fn.returns.map !== undefined) {
      fail(`${field} mapped status returns cannot use an output resource`);
    }
    if (isObject(fn.returns) && fn.returns.bytes !== undefined &&
        outputCount > 0) {
      fail(`${field} byte returns cannot also use an output resource`);
    }

    if (isObject(fn.returns) && fn.returns.error !== undefined) {
      const errorResource = fn.returns.error.resource;
      const matches = fn.args.filter((argument) =>
        isObject(argument) &&
        (argument.resource === errorResource ||
         argument.outResource === errorResource)
      );
      if (matches.length !== 1) {
        fail(
          `${field}.returns.error.resource must match exactly one resource argument`
        );
      }
    }

    const producedNames = [];
    if (isObject(fn.returns) && fn.returns.resource !== undefined) {
      producedNames.push(fn.returns.resource);
    }
    for (const argument of fn.args) {
      if (isObject(argument) && argument.outResource !== undefined) {
        producedNames.push(argument.outResource);
      }
    }
    for (const producedName of producedNames) {
      const produced = resources.get(producedName);
      if (!produced.dependsOn) continue;
      const parents = fn.args.filter((argument) =>
        isObject(argument) && argument.resource === produced.dependsOn
      );
      if (parents.length !== 1) {
        fail(
          `${field} producing ${producedName} must have exactly one ` +
          `${produced.dependsOn} resource input`
        );
      }
    }
  }
  return manifest;
}

function loadManifest(manifestPath) {
  let manifest;
  try {
    manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  } catch (error) {
    fail(`could not read manifest '${manifestPath}': ${error.message}`);
  }
  return validateManifest(manifest);
}

function cString(value) {
  return JSON.stringify(value);
}

function cType(type, argument = false) {
  switch (type) {
    case 'void': return 'void';
    case 'bool': return 'bool';
    case 'i8': return 'int8_t';
    case 'u8': return 'uint8_t';
    case 'i16': return 'int16_t';
    case 'u16': return 'uint16_t';
    case 'i32': return 'int32_t';
    case 'u32': return 'uint32_t';
    case 'i64': return 'int64_t';
    case 'u64': return 'uint64_t';
    case 'isize': return 'intptr_t';
    case 'usize': return 'uintptr_t';
    case 'f32': return 'float';
    case 'f64': return 'double';
    case 'cstr': return argument ? 'char *' : 'const char *';
    default: fail(`internal error: unsupported type '${type}'`);
  }
}

function cDeclaration(type, name, argument = false) {
  const separator = type === 'cstr' ? '' : ' ';
  return `${cType(type, argument)}${separator}${name}`;
}

function isResourceInput(argument) {
  return isObject(argument) && argument.resource !== undefined;
}

function isOutputResource(argument) {
  return isObject(argument) && argument.outResource !== undefined;
}

function isConstantArgument(argument) {
  return isObject(argument) && argument.const !== undefined;
}

function isNullArgument(argument) {
  return isObject(argument) && argument.null !== undefined;
}

function isCConstantArgument(argument) {
  return isObject(argument) && argument.cConstant !== undefined;
}

function isBytesArgument(argument) {
  return isObject(argument) && argument.bytes !== undefined;
}

function isHiddenArgument(argument) {
  return isOutputResource(argument) || isConstantArgument(argument) ||
    isNullArgument(argument) || isCConstantArgument(argument);
}

function isResourceReturn(value) {
  return isObject(value) && value.resource !== undefined;
}

function isStatusReturn(value) {
  return isObject(value) && value.status !== undefined;
}

function isBytesReturn(value) {
  return isObject(value) && value.bytes !== undefined;
}

function getResource(manifest, name) {
  const resource = resourceMap(manifest).get(name);
  if (!resource) fail(`internal error: unknown resource '${name}'`);
  return resource;
}

function resourceTypeName(manifest, resource) {
  return `${manifest.package}.${resource.name}`;
}

function resourceDeclaration(resource, name) {
  return `${resource.cType} ${name}`;
}

function returnCType(manifest, value) {
  if (typeof value === 'string') return cType(value);
  if (isResourceReturn(value)) {
    return getResource(manifest, value.resource).cType;
  }
  if (isBytesReturn(value)) return 'const void *';
  return cType(value.status);
}

function argumentDescription(manifest, argument) {
  if (typeof argument === 'string') return argument;
  if (isBytesArgument(argument)) return 'string';
  const resource = getResource(
    manifest,
    argument.resource !== undefined ? argument.resource : argument.outResource
  );
  return resourceTypeName(manifest, resource);
}

function argumentMessage(moduleName, word, index, type) {
  return cString(`${moduleName}.${word} argument ${index + 1} expected ${type}`);
}

function emitFailure(lines, condition, message) {
  lines.push(
    `    if (!(${condition})) {`,
    `        status = toy_fail(state, ${message});`,
    '        goto cleanup;',
    '    }'
  );
}

function emitArgumentDeclarations(lines, manifest, type, index) {
  const argument = `argument_${index}`;
  if (isResourceInput(type)) {
    const resource = getResource(manifest, type.resource);
    lines.push(
      `    void *raw_resource_${index} = NULL;`,
      `    ${resourceDeclaration(resource, argument)} = NULL;`
    );
    return;
  }
  if (isOutputResource(type)) {
    const resource = getResource(manifest, type.outResource);
    lines.push(`    ${resourceDeclaration(resource, argument)} = NULL;`);
    return;
  }
  if (isBytesArgument(type)) {
    lines.push(
      `    const char *bytes_data_${index} = NULL;`,
      `    size_t bytes_size_${index} = 0;`,
      `    ${cDeclaration(type.bytes.length, `bytes_length_${index}`)} = 0;`
    );
    return;
  }
  if (isHiddenArgument(type)) return;
  switch (type) {
    case 'bool':
    case 'i64':
    case 'f32':
    case 'f64':
      lines.push(`    ${cDeclaration(type, argument)} = 0;`);
      break;
    case 'cstr':
      lines.push(
        `    ${cDeclaration(type, argument, true)} = NULL;`,
        `    const char *string_data_${index} = NULL;`,
        `    size_t string_length_${index} = 0;`
      );
      break;
    default:
      lines.push(
        `    int64_t raw_argument_${index} = 0;`,
        `    ${cDeclaration(type, argument)} = 0;`
      );
      break;
  }
}

function sizeFitsType(type, value) {
  if (type === 'u64' || type === 'usize') return 'true';
  const limits = {
    i8: 'INT8_MAX',
    u8: 'UINT8_MAX',
    i16: 'INT16_MAX',
    u16: 'UINT16_MAX',
    i32: 'INT32_MAX',
    u32: 'UINT32_MAX',
    i64: 'INT64_MAX',
    u64: 'UINT64_MAX',
    isize: 'INTPTR_MAX',
    usize: 'UINTPTR_MAX',
  };
  return `${value} <= ${limits[type]}`;
}

function nonnegativeLength(type, value) {
  return type.startsWith('i') ? `${value} >= 0 && ` : '';
}

function lengthFitsSize(type, value, converted) {
  const nonnegative = nonnegativeLength(type, value);
  return `${nonnegative}(uintmax_t)${converted} == (uintmax_t)${value}`;
}

function emitArgumentConversion(
  lines,
  manifest,
  word,
  type,
  index,
  visibleIndex,
  depth
) {
  const argument = `argument_${index}`;
  const raw = `raw_argument_${index}`;
  const message = argumentMessage(
    manifest.package,
    word,
    visibleIndex,
    argumentDescription(manifest, type)
  );
  if (isResourceInput(type)) {
    const resource = getResource(manifest, type.resource);
    emitFailure(
      lines,
      `toy_get_resource(state, ${depth}, ` +
        `${cString(resourceTypeName(manifest, resource))}, ` +
        `&raw_resource_${index})`,
      message
    );
    lines.push(`    ${argument} = raw_resource_${index};`);
    return;
  }
  if (isBytesArgument(type)) {
    emitFailure(
      lines,
      `toy_get_string(state, ${depth}, &bytes_data_${index}, ` +
        `&bytes_size_${index}) && ` +
        sizeFitsType(type.bytes.length, `bytes_size_${index}`),
      message
    );
    lines.push(
      `    bytes_length_${index} = ` +
        `(${cType(type.bytes.length)})bytes_size_${index};`
    );
    return;
  }
  switch (type) {
    case 'bool':
      emitFailure(lines, `toy_get_bool(state, ${depth}, &${argument})`, message);
      break;
    case 'i8':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= INT8_MIN && ${raw} <= INT8_MAX`,
        message
      );
      lines.push(`    ${argument} = (int8_t)${raw};`);
      break;
    case 'u8':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= 0 && ${raw} <= UINT8_MAX`,
        message
      );
      lines.push(`    ${argument} = (uint8_t)${raw};`);
      break;
    case 'i16':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= INT16_MIN && ${raw} <= INT16_MAX`,
        message
      );
      lines.push(`    ${argument} = (int16_t)${raw};`);
      break;
    case 'u16':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= 0 && ${raw} <= UINT16_MAX`,
        message
      );
      lines.push(`    ${argument} = (uint16_t)${raw};`);
      break;
    case 'i32':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= INT32_MIN && ${raw} <= INT32_MAX`,
        message
      );
      lines.push(`    ${argument} = (int32_t)${raw};`);
      break;
    case 'u32':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= 0 && (uint64_t)${raw} <= UINT32_MAX`,
        message
      );
      lines.push(`    ${argument} = (uint32_t)${raw};`);
      break;
    case 'i64':
      emitFailure(lines, `toy_get_int(state, ${depth}, &${argument})`, message);
      break;
    case 'u64':
      emitFailure(lines, `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= 0`, message);
      lines.push(`    ${argument} = (uint64_t)${raw};`);
      break;
    case 'isize':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= INTPTR_MIN && ${raw} <= INTPTR_MAX`,
        message
      );
      lines.push(`    ${argument} = (intptr_t)${raw};`);
      break;
    case 'usize':
      emitFailure(
        lines,
        `toy_get_int(state, ${depth}, &${raw}) && ${raw} >= 0 && (uint64_t)${raw} <= UINTPTR_MAX`,
        message
      );
      lines.push(`    ${argument} = (uintptr_t)${raw};`);
      break;
    case 'f32':
      emitFailure(
        lines,
        `binding_get_number(state, ${depth}, &raw_number_${index}) && ` +
          `(!isfinite(raw_number_${index}) || ` +
          `(raw_number_${index} >= -FLT_MAX && raw_number_${index} <= FLT_MAX))`,
        message
      );
      lines.push(`    ${argument} = (float)raw_number_${index};`);
      break;
    case 'f64':
      emitFailure(lines, `binding_get_number(state, ${depth}, &${argument})`, message);
      break;
    case 'cstr':
      emitFailure(
        lines,
        `toy_get_string(state, ${depth}, &string_data_${index}, &string_length_${index}) && ` +
          `(string_length_${index} == 0 || ` +
          `!memchr(string_data_${index}, '\\0', string_length_${index}))`,
        message
      );
      lines.push(
        `    ${argument} = malloc(string_length_${index} + 1);`,
        `    if (!${argument}) {`,
        `        status = toy_fail(state, ${cString(`${manifest.package}.${word} could not copy argument ${visibleIndex + 1}`)});`,
        '        goto cleanup;',
        '    }',
        `    memcpy(${argument}, string_data_${index}, string_length_${index});`,
        `    ${argument}[string_length_${index}] = '\\0';`
      );
      break;
    default:
      fail(`internal error: unsupported argument type '${type}'`);
  }
}

function emitScalarReturn(lines, moduleName, word, type) {
  const prefix = `${moduleName}.${word}`;
  switch (type) {
    case 'bool':
      lines.push('    status = toy_push_bool(state, result);');
      break;
    case 'i8':
    case 'u8':
    case 'i16':
    case 'u16':
    case 'i32':
    case 'u32':
    case 'i64':
    case 'isize':
      lines.push('    status = toy_push_int(state, (int64_t)result);');
      break;
    case 'u64':
    case 'usize':
      lines.push(
        '    if ((uint64_t)result > INT64_MAX) {',
        `        status = toy_fail(state, ${cString(`${prefix} returned ${type} outside Toy's range`)});`,
        '    } else {',
        '        status = toy_push_int(state, (int64_t)result);',
        '    }'
      );
      break;
    case 'f32':
    case 'f64':
      lines.push('    status = toy_push_float(state, (double)result);');
      break;
    case 'cstr':
      lines.push(
        '    if (!result) {',
        `        status = toy_fail(state, ${cString(`${prefix} returned a null cstr`)});`,
        '    } else if (!result_copy) {',
        `        status = toy_fail(state, ${cString(`${prefix} could not copy its cstr result`)});`,
        '    } else {',
        '        status = toy_push_string(state, result_copy, result_length);',
        '    }'
      );
      break;
    default:
      fail(`internal error: unsupported return type '${type}'`);
  }
}

function emitResourcePush(
  lines,
  manifest,
  resource,
  value,
  parent,
  prefix
) {
  lines.push(
    `    if (!${value}) {`,
    `        status = toy_fail(state, ${cString(`${prefix} returned a null ${resourceTypeName(manifest, resource)}`)});`,
    '    } else {',
    `        status = toy_push_resource(state, ` +
      `${cString(resourceTypeName(manifest, resource))}, ${value}, ` +
      `binding_destroy_resource_${resource.index}, ${parent});`,
    '        if (status == TOY_OK) {',
    `            ${value} = NULL;`,
    ...(parent === 'NULL' ? [] : [`            ${parent} = NULL;`]),
    '        }',
    '    }'
  );
}

function statusCondition(value) {
  const codes = value.success || Object.keys(value.map).map(Number);
  return codes
    .map((code) => `result == (${cType(value.status)})${code}`)
    .join(' || ');
}

function emitMappedStatus(lines, value) {
  const entries = Object.entries(value.map);
  for (const [index, [code, mapped]] of entries.entries()) {
    const keyword = index === 0 ? 'if' : 'else if';
    lines.push(
      `    ${keyword} (result == (${cType(value.status)})${code}) {`,
      `        status = toy_push_bool(state, ${mapped ? 'true' : 'false'});`,
      '    }'
    );
  }
}

function constantExpression(argument) {
  const type = argument.const;
  let value;
  if (type === 'bool') value = argument.value ? 'true' : 'false';
  else value = String(argument.value);
  return `(${cType(type)})${value}`;
}

function callArgumentExpressions(argument, index) {
  if (isOutputResource(argument)) return [`&argument_${index}`];
  if (isConstantArgument(argument)) return [constantExpression(argument)];
  if (isNullArgument(argument)) return ['NULL'];
  if (isCConstantArgument(argument)) return [argument.cConstant];
  if (isBytesArgument(argument)) {
    return [`bytes_data_${index}`, `bytes_length_${index}`];
  }
  return [`argument_${index}`];
}

function producedResourceEntry(manifest, fn) {
  if (isResourceReturn(fn.returns)) {
    return {
      resource: getResource(manifest, fn.returns.resource),
      value: 'result',
    };
  }
  const entry = fn.args
    .map((argument, argIndex) => ({argument, argIndex}))
    .find((candidate) => isOutputResource(candidate.argument));
  if (!entry) return null;
  return {
    resource: getResource(manifest, entry.argument.outResource),
    value: `argument_${entry.argIndex}`,
  };
}

function dependencyInput(fn, resource) {
  if (!resource.dependsOn) return null;
  const visible = fn.args.filter((argument) => !isHiddenArgument(argument));
  const visibleIndex = visible.findIndex(
    (argument) => isResourceInput(argument) &&
      argument.resource === resource.dependsOn
  );
  return {
    depth: visible.length - visibleIndex - 1,
    variable: 'resource_parent',
  };
}

function statusErrorExpression(fn) {
  if (!isStatusReturn(fn.returns) || !fn.returns.error) return 'NULL';
  const resourceName = fn.returns.error.resource;
  const index = fn.args.findIndex((argument) =>
    isObject(argument) &&
      (argument.resource === resourceName ||
       argument.outResource === resourceName)
  );
  return `argument_${index} ? ` +
    `${fn.returns.error.function}(argument_${index}) : NULL`;
}

function renderFunction(manifest, fn, index) {
  const word = fn.word || fn.name;
  const prefix = `${manifest.package}.${word}`;
  const visibleArgs = fn.args.filter((argument) => !isHiddenArgument(argument));
  const produced = producedResourceEntry(manifest, fn);
  const dependency = produced
    ? dependencyInput(fn, produced.resource)
    : null;
  const callArguments = fn.args.flatMap(callArgumentExpressions);
  const call = `${fn.name}(${callArguments.join(', ')})`;
  const lines = [
    `static toy_status binding_word_${index}(toy_state *state) {`,
    '    toy_status status = TOY_ERROR;',
  ];

  for (const [argIndex, type] of fn.args.entries()) {
    emitArgumentDeclarations(lines, manifest, type, argIndex);
    if (type === 'f32') lines.push(`    double raw_number_${argIndex} = 0.0;`);
  }
  if (fn.returns !== 'void') {
    lines.push(`    ${returnCType(manifest, fn.returns)} result = 0;`);
  }
  if (fn.returns === 'cstr') {
    lines.push(
      '    char *result_copy = NULL;',
      '    size_t result_length = 0;'
    );
  }
  if (isBytesReturn(fn.returns)) {
    lines.push(
      `    ${cDeclaration(fn.returns.bytes.lengthType, `result_length_raw`)} = 0;`,
      '    size_t result_length = 0;',
      '    char *result_copy = NULL;'
    );
  }
  if (isStatusReturn(fn.returns)) {
    lines.push('    bool result_succeeded = false;');
  }
  if (dependency) lines.push('    toy_value *resource_parent = NULL;');
  if (fn.args.length > 0 || fn.returns !== 'void') lines.push('');

  let visibleIndex = 0;
  for (const [argIndex, type] of fn.args.entries()) {
    if (isHiddenArgument(type)) continue;
    emitArgumentConversion(
      lines,
      manifest,
      word,
      type,
      argIndex,
      visibleIndex,
      visibleArgs.length - visibleIndex - 1
    );
    visibleIndex++;
  }
  if (fn.returns === 'void') lines.push(`    ${call};`);
  else lines.push(`    result = ${call};`);
  lines.push('    status = TOY_OK;');

  if (fn.returns === 'cstr') {
    lines.push(
      '    if (!result) {',
      `        status = toy_fail(state, ${cString(`${prefix} returned a null cstr`)});`,
      '    } else {',
      '        result_length = strlen(result);',
      '        result_copy = malloc(result_length + 1);',
      '        if (!result_copy) {',
      `            status = toy_fail(state, ${cString(`${prefix} could not copy its cstr result`)});`,
      '        } else {',
      '            memcpy(result_copy, result, result_length + 1);',
      '        }',
      '    }'
    );
  }

  if (isBytesReturn(fn.returns)) {
    const bytes = fn.returns.bytes;
    const lengthCall = `${bytes.lengthFunction}(${callArguments.join(', ')})`;
    lines.push(
      `    result_length_raw = ${lengthCall};`,
      '    result_length = (size_t)result_length_raw;',
      `    if (!(${lengthFitsSize(bytes.lengthType, 'result_length_raw', 'result_length')})) {`,
      `        status = toy_fail(state, ${cString(`${prefix} returned an invalid byte length`)});`,
      '    } else if (!result) {',
      `        status = toy_fail(state, ${cString(`${prefix} returned null bytes`)});`,
      '    } else {',
      '        if (result_length > 0) {',
      '            result_copy = malloc(result_length);',
      '            if (!result_copy) {',
      `                status = toy_fail(state, ${cString(`${prefix} could not copy its byte result`)});`,
      '            } else {',
      '                memcpy(result_copy, result, result_length);',
      '            }',
      '        }',
      '    }'
    );
  }

  if (isStatusReturn(fn.returns)) {
    lines.push(
      `    result_succeeded = ${statusCondition(fn.returns)};`,
      '    if (!result_succeeded) {',
      `        status = binding_fail_status(state, ${cString(prefix)}, ` +
        `(long long)result, ${statusErrorExpression(fn)});`,
      '    }'
    );
  }

  if (dependency) {
    lines.push(
      `    if (${produced.value}) {`,
      `        resource_parent = toy_value_retain(state, ${dependency.depth});`,
      '        if (!resource_parent && status == TOY_OK) {',
      `            status = toy_fail(state, ${cString(`${prefix} could not retain its resource dependency`)});`,
      '        }',
      '    }'
    );
  }

  if (visibleArgs.length > 0) {
    lines.push(
      '    if (!toy_pop(state, ' + visibleArgs.length + ')) {',
      `        status = toy_fail(state, ${cString(`${prefix} failed to pop its inputs`)});`,
      '        goto cleanup;',
      '    }'
    );
  }
  lines.push('    if (status != TOY_OK) goto cleanup;');

  if (produced) {
    emitResourcePush(
      lines,
      manifest,
      produced.resource,
      produced.value,
      dependency ? dependency.variable : 'NULL',
      prefix
    );
  } else if (isStatusReturn(fn.returns) && fn.returns.map !== undefined) {
    emitMappedStatus(lines, fn.returns);
  } else if (isBytesReturn(fn.returns)) {
    lines.push(
      '    status = toy_push_string(state,',
      '                             result_copy ? result_copy : "",',
      '                             result_length);'
    );
  } else if (typeof fn.returns === 'string' && fn.returns !== 'void') {
    emitScalarReturn(lines, manifest.package, word, fn.returns);
  }
  lines.push('    goto cleanup;', '', 'cleanup:');
  for (const [argIndex, type] of fn.args.entries()) {
    if (type === 'cstr') lines.push(`    free(argument_${argIndex});`);
    if (isOutputResource(type)) {
      const resource = getResource(manifest, type.outResource);
      lines.push(
        `    if (argument_${argIndex}) {`,
        `        binding_destroy_resource_${resource.index}(` +
          `argument_${argIndex}, ` +
          `${dependency ? dependency.variable : 'NULL'});`,
        `        argument_${argIndex} = NULL;`,
        ...(dependency ? [`        ${dependency.variable} = NULL;`] : []),
        '    }'
      );
    }
  }
  if (fn.returns === 'cstr') lines.push('    free(result_copy);');
  if (isBytesReturn(fn.returns)) lines.push('    free(result_copy);');
  if (isResourceReturn(fn.returns)) {
    const resource = getResource(manifest, fn.returns.resource);
    lines.push(
      '    if (result) {',
      `        binding_destroy_resource_${resource.index}(` +
        `result, ${dependency ? dependency.variable : 'NULL'});`,
      '        result = NULL;',
      ...(dependency ? [`        ${dependency.variable} = NULL;`] : []),
      '    }'
    );
  }
  if (dependency) {
    lines.push(
      `    if (${dependency.variable}) {`,
      `        toy_value_release(${dependency.variable});`,
      '    }'
    );
  }
  lines.push('    return status;', '}', '');
  return lines;
}

function renderBinding(manifest) {
  const needsNumberHelper = manifest.functions.some((fn) =>
    fn.args.some((type) => type === 'f32' || type === 'f64')
  );
  const needsStatusHelper = manifest.functions.some((fn) =>
    isStatusReturn(fn.returns)
  );
  const lines = [
    `/* ${generatedComment} */`,
    '#define TOY_EXTENSION_IMPLEMENTATION',
    '#include "toy.h"',
    '',
    ...manifest.headers.map((header) => `#include "${header}"`),
    '',
    '#include <float.h>',
    '#include <math.h>',
    '#include <stdint.h>',
    '#include <stdio.h>',
    '#include <stdlib.h>',
    '#include <string.h>',
    '',
  ];

  if (needsNumberHelper) {
    lines.push(
      'static bool binding_get_number(toy_state *state, size_t depth,',
      '                               double *value) {',
      '    if (toy_stack_type(state, depth) == TOY_TYPE_FLOAT) {',
      '        return toy_get_float(state, depth, value);',
      '    }',
      '    int64_t integer = 0;',
      '    if (!toy_get_int(state, depth, &integer)) return false;',
      '    *value = (double)integer;',
      '    return true;',
      '}',
      ''
    );
  }

  if (needsStatusHelper) {
    lines.push(
      'static toy_status binding_fail_status(toy_state *state,',
      '                                      const char *word,',
      '                                      long long value,',
      '                                      const char *detail) {',
      '    char message[256];',
      '    if (detail && detail[0] != \'\\0\') {',
      '        snprintf(message, sizeof(message),',
      '                 "%s failed with status %lld: %s",',
      '                 word, value, detail);',
      '    } else {',
      '        snprintf(message, sizeof(message),',
      '                 "%s failed with status %lld", word, value);',
      '    }',
      '    return toy_fail(state, message);',
      '}',
      ''
    );
  }

  for (const [index, resource] of (manifest.resources || []).entries()) {
    lines.push(
      `static void binding_destroy_resource_${index}(void *resource,`,
      '                                       void *userdata) {',
      ...(resource.dependsOn ? [] : ['    (void)userdata;']),
      `    ${resourceDeclaration(resource, 'value')} = resource;`,
      `    (void)${resource.destructor}(value);`,
      ...(resource.dependsOn
        ? ['    toy_value_release((toy_value *)userdata);']
        : []),
      '}',
      ''
    );
  }

  for (const [index, fn] of manifest.functions.entries()) {
    lines.push(...renderFunction(manifest, fn, index));
  }

  lines.push('static const toy_native_word binding_words[] = {');
  for (const [index, fn] of manifest.functions.entries()) {
    lines.push(
      `    {.name = ${cString(fn.word || fn.name)}, .callback = binding_word_${index}},`
    );
  }
  lines.push(
    '};',
    '',
    'static const toy_extension binding_extension = {',
    '    sizeof(toy_extension),',
    `    ${cString(manifest.package)},`,
    '    binding_words,',
    '    sizeof(binding_words) / sizeof(binding_words[0]),',
    '};',
    '',
    'TOY_EXTENSION_EXPORT const toy_extension *toy_extension_init(',
    '    uint32_t abi_version, const toy_extension_api *api) {',
    '    if (!toy_extension_bind(abi_version, api)) return NULL;',
    '    return &binding_extension;',
    '}',
    ''
  );
  return lines.join('\n');
}

function main() {
  const args = process.argv.slice(2);
  let check = false;
  let expectedPackage = null;
  const positional = [];
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--check') {
      check = true;
    } else if (args[i] === '--package' && i + 1 < args.length) {
      expectedPackage = args[++i];
    } else {
      positional.push(args[i]);
    }
  }
  if (positional.length !== 2) {
    console.error(
      'usage: toy-bindgen [--check] [--package name] <manifest.json> <output.c>'
    );
    process.exitCode = 2;
    return;
  }

  const manifestPath = path.resolve(positional[0]);
  const outputPath = path.resolve(positional[1]);
  const manifest = loadManifest(manifestPath);
  if (expectedPackage !== null && manifest.package !== expectedPackage) {
    fail(
      `manifest package '${manifest.package}' does not match directory package '${expectedPackage}'`
    );
  }
  const expected = renderBinding(manifest);
  if (check) {
    const actual = fs.existsSync(outputPath)
      ? fs.readFileSync(outputPath, 'utf8')
      : null;
    if (actual !== expected) {
      console.error(`out of date: ${outputPath}`);
      process.exitCode = 1;
    } else {
      console.log(`generated binding is up to date: ${outputPath}`);
    }
    return;
  }

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, expected);
  console.log(`wrote ${outputPath}`);
}

if (require.main === module) {
  try {
    main();
  } catch (error) {
    console.error(`error: ${error.message}`);
    process.exitCode = 1;
  }
}

module.exports = { renderBinding, validateManifest };
